######################################################################
# Automatically generated by qmake (2.01a) Fri May 3 23:32:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += leddialog.h
FORMS += leddialog.ui
SOURCES += leddialog.cpp main.cpp
TRANSLATIONS += zh_CN.ts
